# Generated by Django 2.0.6 on 2018-07-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_text', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_text', models.CharField(max_length=200)),
                ('numero_text', models.IntegerField()),
                ('complemento_text', models.CharField(max_length=200)),
                ('bairro_text', models.CharField(max_length=200)),
                ('cidade_text', models.CharField(max_length=200)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prato_text', models.CharField(max_length=200)),
                ('prato_numero', models.IntegerField()),
                ('tam_text', models.CharField(max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='data de adiçao')),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
