# Generated by Django 2.0.6 on 2018-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prato_numero', models.IntegerField()),
                ('tam_text', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='prato_numero',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tam_text',
        ),
        migrations.AlterField(
            model_name='produto',
            name='pub_date',
            field=models.DateField(verbose_name='Data de adição'),
        ),
    ]
