# Generated by Django 2.0.6 on 2018-07-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0002_auto_20180706_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='prato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.NumeroProduto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data de adição'),
        ),
    ]
