# Generated by Django 2.0.6 on 2018-07-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0003_auto_20180706_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroproduto',
            name='tam_text',
        ),
        migrations.AddField(
            model_name='produto',
            name='tam_text',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
