# Generated by Django 2.0.6 on 2018-07-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0004_auto_20180706_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeroproduto',
            old_name='prato_numero',
            new_name='pratonumero',
        ),
    ]
