# Generated by Django 2.0.6 on 2018-07-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0005_auto_20180707_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='01-01-2018', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemPedidos',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sitemarmileve.Pedidos', unique=True)),
                ('data', models.DateField(auto_now=True)),
                ('prato', models.CharField(max_length=200)),
                ('tamanho', models.CharField(max_length=1)),
                ('qtd', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Cliente'),
        ),
    ]
