# Generated by Django 2.0.6 on 2018-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0006_auto_20180714_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cpf',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
