# Generated by Django 2.0.6 on 2018-07-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0008_auto_20180714_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPedidos',
            new_name='ItemPedido',
        ),
    ]
