# Generated by Django 2.0.6 on 2018-07-14 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0009_auto_20180714_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Pedido'),
            preserve_default=False,
        ),
    ]
