# Generated by Django 2.0.6 on 2018-07-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0010_itempedido_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='item',
            new_name='pedido',
        ),
    ]
