# Generated by Django 2.0.6 on 2018-07-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0011_auto_20180714_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
