# Generated by Django 2.0.6 on 2018-07-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0012_auto_20180714_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido',
            new_name='id_pedido',
        ),
    ]
