# Generated by Django 2.0.6 on 2018-07-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0013_auto_20180717_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='id_pedido',
            new_name='pedido_id',
        ),
    ]
