# Generated by Django 2.0.6 on 2018-07-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0014_auto_20180717_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='nome',
            new_name='id_cliente',
        ),
    ]
