# Generated by Django 2.0.6 on 2018-07-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0015_auto_20180717_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Cliente'),
        ),
    ]
