# Generated by Django 2.0.6 on 2018-07-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0016_auto_20180717_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_text',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='bairro_text',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='cidade_text',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='complemento_text',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='endereco_text',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='numero_text',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='tam_text',
            new_name='tam',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='prato_text',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prato',
            field=models.CharField(max_length=200),
        ),
    ]
