# Generated by Django 2.0.6 on 2018-07-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0019_auto_20180718_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prato', models.CharField(max_length=200)),
                ('pratonumero', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('p', 'Pequeno'), ('g', 'Grande'), ('s', 'Sopa')], max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_ativo', models.DateField(auto_now_add=True)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Prato')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pratonumero',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='nome_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='data',
            new_name='datapedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Prato'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Tamanho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='NumeroProduto',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='estoque',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Prato'),
        ),
    ]
