# Generated by Django 2.0.6 on 2018-07-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0020_auto_20180718_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='datapedido',
            new_name='data_pedido',
        ),
    ]
