# Generated by Django 2.0.6 on 2018-07-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0021_auto_20180718_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_ativo', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='prato',
        ),
        migrations.AddField(
            model_name='prato',
            name='tamanho',
            field=models.CharField(choices=[('p', 'Pequeno'), ('g', 'Grande'), ('s', 'Sopa')], default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(choices=[('p', 'Pequeno'), ('g', 'Grande'), ('s', 'Sopa')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
        migrations.AddField(
            model_name='preco',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemarmileve.Prato'),
        ),
    ]
