# Generated by Django 2.0.6 on 2018-07-19 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0022_auto_20180718_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_fabricacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='qtd',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='tamanho',
            field=models.CharField(choices=[('p', 'Pequeno'), ('g', 'Grande'), ('s', 'Sopa')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
