# Generated by Django 2.0.6 on 2018-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0023_auto_20180719_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='endereco_ativo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
