# Generated by Django 2.0.6 on 2018-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0025_auto_20180807_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
