# Generated by Django 2.0.6 on 2018-08-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0028_auto_20180810_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquecheck',
            name='source',
            field=models.CharField(default='pedidos', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoquecheck',
            name='sourceid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoquecheck',
            name='tamanho',
            field=models.CharField(default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoquecheck',
            name='qtd',
            field=models.IntegerField(),
        ),
    ]
