# Generated by Django 2.0.6 on 2018-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0029_auto_20180811_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='preco',
            name='prato',
        ),
        migrations.AddField(
            model_name='preco',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande'), ('S', 'Sopa')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preco',
            name='data_ativo',
            field=models.DateField(),
        ),
    ]
