# Generated by Django 2.0.6 on 2018-08-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0030_auto_20180811_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(default='11'),
            preserve_default=False,
        ),
    ]
