# Generated by Django 2.0.6 on 2018-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0032_auto_20180813_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande'), ('S', 'Sopa')], max_length=1),
        ),
    ]
