# Generated by Django 2.0.6 on 2018-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0033_auto_20180813_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='pedidoid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='estoqueid',
            field=models.IntegerField(default=None),
        ),
    ]
