# Generated by Django 2.0.6 on 2018-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0034_auto_20180814_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='pedidoid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='estoqueid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
