# Generated by Django 2.0.6 on 2018-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0036_auto_20180814_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('valorfrete', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
