# Generated by Django 2.0.6 on 2018-08-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0037_auto_20180828_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
