# Generated by Django 2.0.6 on 2018-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0038_auto_20180830_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='estoquecheck',
            name='qtd',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='estoquecheck',
            name='sourceid',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='prato',
            name='pratonumero',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
