# Generated by Django 2.0.6 on 2018-09-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0040_auto_20180910_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquecheck',
            name='sourceid',
            field=models.SmallIntegerField(),
        ),
    ]
