# Generated by Django 2.0.6 on 2018-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemarmileve', '0042_auto_20180910_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qtd',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='qtd',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='prato',
            name='pratonumero',
            field=models.SmallIntegerField(),
        ),
    ]
